### PR TITLE
Add option to run `exec` synchronously

### PR DESCRIPTION
**Pull request by nathanbrauer**
E.g. with the right additional plugins, one could be sure composer has finished building before attempting to run unit tests or compilers.

Also now validated through `jslint`.

### CODE REVIEW

**Comment by nathanbrauer** [comment]
GitHub's "Files Changed" makes it very difficult to understand what exactly has changed.

Here's a better diff view of the entire changes (three images which you can click to view full-size):

page-1
page-2
page-3

Or you can add ?w=1 to have GitHub ignore less meaningful whitespace changes so it produces a clearer picture:
 - https://github.com/cyberdummy/gulp-composer/pull/5/files?w=1

Or you can look at the changes for each commit individually:
 - https://github.com/Marketera/gulp-composer/commit/6af6143dda4ff7d00e72b149aaca69e80dc33ef0
 - https://github.com/Marketera/gulp-composer/commit/a9c50a03ecfeb87c557ca6d84e9a66a54564e467?w=1

**Comment by nathanbrauer** [comment]
Let me know if you have any questions, @cyberdummy  :)

**Comment by cyberdummy** [comment]
Thanks did not know about the w=1 trick. Was using the separate commits.

**Comment by nathanbrauer** [comment]
No prob.  I noticed you bumped it to 0.3.0, but then you bumped it again to 0.4.0 without any other commits in-between. It's not a problem but just wondering what the reason was for that....

**Comment by cyberdummy** [comment]
I messed up my commits and published, the version was 0.3.0 but the code
was still old.

**Comment by nathanbrauer** [comment]
ah

**Pull request merged**
